apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asf-sandbox-workspaces
  namespace: software-factory-sandbox
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
