apiVersion: v1
kind: PersistentVolume
metadata:
  name: asf-sandbox-workspaces-local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: asf-local-hostpath
  hostPath:
    path: /var/local/asf/workspaces
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asf-sandbox-workspaces
  namespace: software-factory-sandbox
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: asf-local-hostpath
  volumeName: asf-sandbox-workspaces-local
  resources:
    requests:
      storage: 10Gi
