QUALITY_GATES = [
    ("requirements", "Requirements Gate", "requirements"),
    ("acceptance_criteria", "Acceptance Criteria Gate", "requirements"),
    ("scope", "Scope Gate", "governance"),
    ("architecture", "Architecture Gate", "architecture"),
    ("ux", "UX Gate", "ux"),
    ("data", "Data Gate", "data"),
    ("api", "API Gate", "api"),
    ("implementation", "Implementation Gate", "implementation"),
    ("code_review", "Code Review Gate", "quality"),
    ("tests", "Test Gate", "testing"),
    ("traceability", "Traceability Gate", "governance"),
    ("visual_qa", "Visual QA Gate", "ux"),
    ("accessibility", "Accessibility Gate", "accessibility"),
    ("security", "Security Gate", "security"),
    ("documentation", "Documentation Gate", "documentation"),
    ("homologation_package", "Homologation Package Gate", "release"),
    ("human_approval", "Human Approval Gate", "approval"),
]
